version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq  # Wichtig für DNS-Auflösung
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_ERLANG_COOKIE: "SECURE_COOKIE"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - tun_net

  container_a:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: container_a/Dockerfile
    cap_add: [NET_ADMIN, SYS_ADMIN]
    devices: ["/dev/net/tun"]
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      - tun_net

  container_b:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: container_b/Dockerfile
    cap_add: [NET_ADMIN, SYS_ADMIN]
    devices: ["/dev/net/tun"]
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      - tun_net

networks:
  tun_net:
    driver: bridge
    attachable: true
