version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    networks:
      vpn_net:
        ipv4_address: 172.18.0.2
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"     # AMQP für Python
      - "15672:15672"   # Management UI
      - "15674:15674"   # Web-STOMP für Browser
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_stomp rabbitmq_web_stomp &&
               rabbitmq-server"

  channel-request:
    build:
      context: .
      dockerfile: channel_request/Dockerfile
    networks:
      vpn_net:
        ipv4_address: 172.18.0.5
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    depends_on:
      rabbitmq:
        condition: service_healthy

  channel-response:
    build:
      context: .
      dockerfile: channel_response/Dockerfile
    networks:
      vpn_net:
        ipv4_address: 172.18.0.6
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    depends_on:
      rabbitmq:
        condition: service_healthy

  container_a:
    build:
      context: .
      dockerfile: container_a/Dockerfile
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      vpn_net:
        ipv4_address: 172.18.0.3
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    depends_on:
      rabbitmq:
        condition: service_healthy

  container_b:
    build:
      context: .
      dockerfile: container_b/Dockerfile
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      vpn_net:
        ipv4_address: 172.18.0.4    #innerhalb des Docker Netzwerks
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    depends_on:
      rabbitmq:
        condition: service_healthy

  webclient-dev:
    build:
      context: ./webclient
      dockerfile: Dockerfile.dev
    container_name: webclient-dev
    ports:
      - "5173:5173"            # -> http://localhost:5173
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      vpn_net:
        ipv4_address: 172.18.0.7
    volumes:
      - ./webclient/src:/app/src           # Live-Reload bei Code-Änderungen
      - ./webclient/index.html:/app/index.html
      - /app/node_modules                  # verhindert node_modules-Überschreibung






networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16  # Subnetz muss zur IP-Konfiguration passen
          gateway: 172.18.0.1
